name: Execute Python script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12' # Specify the version of Python you want to use

      - name: Install dependencies
        run: |
          pip install requests
          pip install beautifulsoup4

      - name: Execute Python script
        run: python .github/workflows/scrape.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: opening_hours
          path: opening_hours.ctxt

      - name: Get KS sources
        run: |-
          curl 'https://api-yousee.cognigy.cloud/new/v2.0/knowledgestores/6614e50de571cdd36d7d7899/sources/661e2c0516e3cf86cfeea274' \
            -X PATCH -H "Accept: application/json" \
            -H 'X-API-Key: ${{ secrets.COGNIGY_API_KEY }}' \
            -H "Content-Type: application/json" \
            -d @output/opening_hours.ctxt
        env:
          PYTHON_LOCATION: /opt/hostedtoolcache/Python/3.9.12/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.12/x64/lib
