name: Execute Python script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'  # Run every minute

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12' # Specify the version of Python you want to use

      - name: Install dependencies
        run: |
          pip install requests
          pip install beautifulsoup4

      - name: Extract _id
        id: extract_id
        run: echo "::set-output name=id::$(curl -s -X GET "https://api-yousee.cognigy.cloud/new/v2.0/knowledgestores/6614e50de571cdd36d7d7899/sources" -H "Accept: application/json" -H "X-API-Key: $KEY" -H "Accept: application/json" | jq -r '.items[] | select(.name == "opening_hours.ctxt") | ._id')"

      - name: Log _id
        run: echo "Extracted _id: ${{ steps.extract_id.outputs.id }}"

      - name: Execute Python script
        run: python .github/workflows/scrape.py

      # Debugging steps to verify file creation and content
      - name: Debug Directory
        run: ls -l output

      - name: Debug File
        run: ls -l output/opening_hours.ctxt

      - name: Display File Content
        run: cat output/opening_hours.ctxt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: opening_hours
          path: output/opening_hours.ctxt

      - name: Upload opening_hours source
        run: |-
          curl 'https://api-yousee.cognigy.cloud/new/v2.0/knowledgestores/6614e50de571cdd36d7d7899/sources/upload' \
            -X POST -H "Accept: application/json" \
            -H 'X-API-Key: ${{ secrets.COGNIGY_API_KEY }}' \
            -H "Content-Type: multipart/form-data" \
            -F "file=@output/opening_hours.ctxt"
        env:
          PYTHON_LOCATION: /opt/hostedtoolcache/Python/3.9.12/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.12/x64/lib
          OPENING_HOURS_ID: ${{ steps.extract_id.outputs.id }}

