name: Execute Python script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'  # Run every minute

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12' # Specify the version of Python you want to use

      - name: Install dependencies
        run: |
          pip install requests
          pip install beautifulsoup4

      - name: Extract sources from KS_Main
        id: extract_sources
        run: |
          response=$(curl -X GET "https://api-yousee.cognigy.cloud/new/v2.0/knowledgestores/6614e50de571cdd36d7d7899/sources" \
            -H "Accept: application/json" \
            -H "X-API-Key: ${{ secrets.COGNIGY_API_KEY }}")
          echo "API Response: $response"  # Log the API response
          opening_hours_id=$(echo $response | python -c "import sys, json; print(json.load(sys.stdin)['items'][0]['_id'])")
          echo "Extracted opening_hours_id: $opening_hours_id"  # Log the extracted id
          echo "::set-output name=opening_hours_id::$opening_hours_id"

      - name: Execute Python script
        run: python .github/workflows/scrape.py

      # Debugging steps to verify file creation and content
      - name: Debug Directory
        run: ls -l output

      - name: Debug File
        run: ls -l output/opening_hours.ctxt

      - name: Display File Content
        run: cat output/opening_hours.ctxt

      - name: Delete opening_hours.ctxt
        run: |-
          echo "Opening hours ID: ${{ steps.extract_sources.outputs.opening_hours_id }}"
          curl -X DELETE "https://api-yousee.cognigy.cloud/new/v2.0/knowledgestores/6614e50de571cdd36d7d7899/sources/${{ steps.extract_sources.outputs.opening_hours_id }}" \
            -H "Accept: application/json" \
            -H "X-API-Key: ${{ secrets.COGNIGY_API_KEY }}"

      - name: Upload opening_hours source
        run: |-
          curl 'https://api-yousee.cognigy.cloud/new/v2.0/knowledgestores/6614e50de571cdd36d7d7899/sources/upload' \
            -X POST -H "Accept: application/json" \
            -H 'X-API-Key: ${{ secrets.COGNIGY_API_KEY }}' \
            -H "Content-Type: multipart/form-data" \
            -F "file=@output/opening_hours.ctxt"
        env:
          PYTHON_LOCATION: /opt/hostedtoolcache/Python/3.9.12/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.12/x64/lib

